use_frameworks!

platform :ios, '8.0'

target 'SCResponderChainPasser_Example' do
  pod 'SCResponderChainPasser', :path => '../'

  target 'SCResponderChainPasser_Tests' do
    inherit! :search_paths

    
  end
end
